// apps/web/src/components/ModeSelectionLanding.tsx
interface ModeSelectionLandingProps {
  onSelectMode: (mode: 'long_term' | 'quick') => void
}

export function ModeSelectionLanding({ onSelectMode }: ModeSelectionLandingProps) {
  return (
    <div className="landing-container">
      <div className="landing-header">
        <h1>🍔 EatOrNot</h1>
        <p>你的智能饮食决策助手</p>
      </div>

      <div className="landing-cards">
        <div className="landing-card" onClick={() => onSelectMode('long_term')}>
          <div className="landing-card-icon">📊</div>
          <h2>长期管理我的饮食</h2>
          <p>建立个人档案，追踪体重、预算、营养目标</p>
          <ul>
            <li>设定减脂/增肌/维持目标</li>
            <li>追踪每日热量和预算</li>
            <li>记录用餐历史</li>
            <li>个性化推荐</li>
          </ul>
          <button className="btn-landing">开始建档</button>
        </div>

        <div className="landing-card" onClick={() => onSelectMode('quick')}>
          <div className="landing-card-icon">⚡</div>
          <h2>就这顿帮我选一下</h2>
          <p>快速选择，无需注册，30秒搞定</p>
          <ul>
            <li>告诉我你的预算和心情</li>
            <li>3个方案即刻呈现</li>
            <li>无需建档</li>
            <li>快速下单</li>
          </ul>
          <button className="btn-landing btn-quick">快速选择</button>
        </div>
      </div>
    </div>
  )
}

// apps/web/src/components/ModeSelectionLanding.vue
<script setup lang="ts">
import { Card, CardContent, CardDescription, CardHeader, CardTitle, Button } from '@/components/ui'

defineEmits<{
  'select-mode': [mode: 'long_term' | 'quick']
}>()
</script>

<template>
  <div class="min-h-screen bg-gradient-to-br from-orange-50 to-amber-50 flex items-center justify-center p-4">
    <div class="max-w-4xl w-full">
      <div class="text-center mb-12">
        <h1 class="text-5xl font-bold text-gray-900 mb-3">🍔 EatOrNot</h1>
        <p class="text-lg text-gray-500">你的智能饮食决策助手</p>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card class="cursor-pointer hover:shadow-lg hover:-translate-y-1 transition-all duration-200 border-orange-200" @click="$emit('select-mode', 'long_term')">
          <CardHeader>
            <div class="text-4xl mb-2">📊</div>
            <CardTitle class="text-xl">长期管理我的饮食</CardTitle>
            <CardDescription>建立个人档案，追踪体重、预算、营养目标</CardDescription>
          </CardHeader>
          <CardContent>
            <ul class="space-y-2 text-sm text-gray-600 mb-6">
              <li class="flex items-center gap-2"><span class="text-orange-500">✓</span> 设定减脂/增肌/维持目标</li>
              <li class="flex items-center gap-2"><span class="text-orange-500">✓</span> 追踪每日热量和预算</li>
              <li class="flex items-center gap-2"><span class="text-orange-500">✓</span> 记录用餐历史</li>
              <li class="flex items-center gap-2"><span class="text-orange-500">✓</span> 个性化推荐</li>
            </ul>
            <Button class="w-full" size="lg">开始建档</Button>
          </CardContent>
        </Card>
        <Card class="cursor-pointer hover:shadow-lg hover:-translate-y-1 transition-all duration-200 border-amber-200" @click="$emit('select-mode', 'quick')">
          <CardHeader>
            <div class="text-4xl mb-2">⚡</div>
            <CardTitle class="text-xl">就这顿帮我选一下</CardTitle>
            <CardDescription>快速选择，无需注册，30秒搞定</CardDescription>
          </CardHeader>
          <CardContent>
            <ul class="space-y-2 text-sm text-gray-600 mb-6">
              <li class="flex items-center gap-2"><span class="text-amber-500">✓</span> 告诉我你的预算和心情</li>
              <li class="flex items-center gap-2"><span class="text-amber-500">✓</span> 3个方案即刻呈现</li>
              <li class="flex items-center gap-2"><span class="text-amber-500">✓</span> 无需建档</li>
              <li class="flex items-center gap-2"><span class="text-amber-500">✓</span> 快速下单</li>
            </ul>
            <Button variant="outline" class="w-full border-amber-300 text-amber-700 hover:bg-amber-50" size="lg">快速选择</Button>
          </CardContent>
        </Card>
      </div>
      <p class="text-center text-xs text-gray-400 mt-8">⚕️ 本工具仅供参考，不构成医疗建议。</p>
    </div>
  </div>
</template>
