// apps/web/src/components/OrderConfirmModal.tsx
import { useState } from 'react'
import { createOrder, type RecommendationPlan } from '../api/client'

export function OrderConfirmModal({
  plan,
  onClose,
  onOrderComplete,
}: {
  plan: RecommendationPlan
  onClose: () => void
  onOrderComplete: (result: { success: boolean; message: string }) => void
}) {
  const [loading, setLoading] = useState(false)
  const [storeCode, setStoreCode] = useState('S001')

  const handleConfirm = async () => {
    setLoading(true)
    try {
      const result = await createOrder(plan, storeCode)
      onOrderComplete(result)
    } catch (err) {
      onOrderComplete({ success: false, message: '下单请求失败' })
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <h2>📋 确认订单</h2>
        <div className="modal-items">
          {plan.items.map((item, i) => (
            <div key={i} className="modal-item">
              <span>{item.name}</span>
              <span>¥{item.price.toFixed(0)} / {item.calories}kcal</span>
            </div>
          ))}
        </div>
        <div className="modal-summary">
          <div>总计: ¥{plan.estimated_price.toFixed(0)}</div>
          <div>总热量: {plan.estimated_calories.toFixed(0)} 千卡</div>
          <div>预算影响: {plan.budget_impact}</div>
        </div>
        <div className="modal-store">
          <label>门店编码: </label>
          <input
            value={storeCode}
            onChange={(e) => setStoreCode(e.target.value)}
            placeholder="S001"
          />
        </div>
        {plan.safety_warnings.length > 0 && (
          <div className="modal-warnings">
            {plan.safety_warnings.map((w, i) => <div key={i}>⚠️ {w}</div>)}
          </div>
        )}
        <div className="modal-actions">
          <button className="btn-cancel" onClick={onClose} disabled={loading}>取消</button>
          <button className="btn-confirm" onClick={handleConfirm} disabled={loading}>
            {loading ? '下单中...' : '确认下单'}
          </button>
        </div>
      </div>
    </div>
  )
}

// apps/web/src/components/OrderConfirmModal.vue
<script setup lang="ts">
import { ref } from 'vue'
import { DialogRoot, DialogContent } from '@/components/ui'
import { Button } from '@/components/ui'
import { createOrder, type RecommendationPlan } from '@/api/client'

const props = defineProps<{ plan: RecommendationPlan }>()
const emit = defineEmits<{
  'order-complete': [result: { success: boolean; message: string }]
  'close': []
}>()

const loading = ref(false)
const storeCode = ref('S001')

async function handleConfirm() {
  loading.value = true
  try {
    const result = await createOrder(props.plan, storeCode.value)
    emit('order-complete', { success: true, message: result.message || '下单成功！' })
  } catch {
    emit('order-complete', { success: false, message: '下单请求失败' })
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <DialogRoot :open="true">
    <DialogContent class="max-w-md">
      <h2 class="text-lg font-semibold mb-4">📋 确认订单</h2>
      <div class="space-y-2 mb-4">
        <div v-for="(item, i) in plan.items" :key="i" class="flex justify-between text-sm">
          <span>{{ item.name }}</span>
          <span>¥{{ item.price.toFixed(0) }} / {{ item.calories }}kcal</span>
        </div>
      </div>
      <div class="border-t pt-3 space-y-1 text-sm">
        <div>总计: ¥{{ plan.estimated_price.toFixed(0) }}</div>
        <div>总热量: {{ plan.estimated_calories.toFixed(0) }} 千卡</div>
        <div>预算影响: {{ plan.budget_impact }}</div>
      </div>
      <div class="flex items-center gap-2 mt-3">
        <label class="text-sm">门店:</label>
        <input v-model="storeCode" class="rounded-md border border-gray-300 px-2 py-1 text-sm w-24" />
      </div>
      <div v-if="plan.safety_warnings.length" class="mt-3 space-y-1">
        <div v-for="w in plan.safety_warnings" :key="w" class="text-sm text-yellow-600">⚠️ {{ w }}</div>
      </div>
      <div class="flex gap-3 mt-6">
        <Button variant="outline" class="flex-1" @click="emit('close')" :disabled="loading">取消</Button>
        <Button class="flex-1" @click="handleConfirm" :disabled="loading">
          {{ loading ? '下单中...' : '确认下单' }}
        </Button>
      </div>
    </DialogContent>
  </DialogRoot>
</template>
