// apps/web/src/components/ProfileCard.vue
<script setup lang="ts">
import { Card, CardContent } from '@/components/ui'
import type { UserProfile } from '@/api/client'

defineProps<{ profile: UserProfile }>()
</script>

<template>
  <Card>
    <CardContent class="p-4 text-sm space-y-1">
      <div class="font-medium">{{ profile.name }}</div>
      <div class="text-muted-foreground">{{ profile.goal }} · ¥{{ profile.daily_budget }}/天</div>
      <div class="text-muted-foreground">{{ profile.height_cm }}cm · {{ profile.weight_kg }}kg · {{ profile.age }}岁</div>
    </CardContent>
  </Card>
</template>

// apps/web/src/components/ProfileCard.tsx
import type { UserProfile } from '../api/client'

export function ProfileCard({ profile }: { profile: UserProfile }) {
  return (
    <div className="card profile-card">
      <h3>👤 {profile.name}</h3>
      <div className="profile-stats">
        <span>身高 {profile.height_cm}cm</span>
        <span>体重 {profile.weight_kg}kg</span>
        <span>年龄 {profile.age}</span>
      </div>
      <div className="profile-goal">
        目标: <strong>{profile.goal === 'lose_weight' ? '减脂' : profile.goal === 'gain_muscle' ? '增肌' : '维持'}</strong>
      </div>
      <div className="profile-budget">
        日预算: ¥{profile.daily_budget}
      </div>
    </div>
  )
}
