// apps/web/src/components/ReminderCard.tsx
import { useState, useEffect } from 'react'
import { useNotifications } from '../hooks/useNotifications'

interface ReminderButton {
  action: string
  label: string
}

interface Reminder {
  reminder_id: string
  type: string
  title: string
  message: string
  urgency: string
  suggested_action: string
  meal_type: string
  buttons: ReminderButton[]
}

interface ReminderCardProps {
  userId?: string
  onAccept?: (reminder: Reminder) => void
  onSnooze?: (reminderId: string) => void
  onDismiss?: (reminderId: string) => void
}

export function ReminderCard({ userId = 'demo-user', onAccept, onSnooze, onDismiss }: ReminderCardProps) {
  const [reminders, setReminders] = useState<Reminder[]>([])
  const [loading, setLoading] = useState(true)
  const [dismissedIds, setDismissedIds] = useState<Set<string>>(new Set())
  const { requestPermission, notify, supported } = useNotifications()
  const [notifiedIds, setNotifiedIds] = useState<Set<string>>(new Set())

  useEffect(() => {
    fetchReminders()
    // 每2分钟检查一次提醒
    const interval = setInterval(fetchReminders, 2 * 60 * 1000)
    return () => clearInterval(interval)
  }, [userId])

  const fetchReminders = async () => {
    try {
      const res = await fetch(`/api/reminders?user_id=${userId}`)
      const data = await res.json()
      // 过滤掉已忽略的提醒
      const filtered = (data.reminders || []).filter(
        (r: Reminder) => !dismissedIds.has(r.reminder_id)
      )
      setReminders(filtered)
      // 发送浏览器通知（去重）
      if (supported) {
        requestPermission()
        const newReminders = filtered.filter((r: Reminder) => !notifiedIds.has(r.reminder_id))
        if (newReminders.length > 0) {
          const latest = newReminders[0]
          notify(latest.title, { body: latest.message })
          setNotifiedIds(prev => new Set([...prev, ...newReminders.map((r: Reminder) => r.reminder_id)]))
        }
      }
    } catch (err) {
      console.error('Failed to fetch reminders:', err)
    }
    setLoading(false)
  }

  const handleAccept = async (reminder: Reminder) => {
    try {
      const res = await fetch(`/api/reminders/${reminder.reminder_id}/accept`, {
        method: 'POST',
      })
      const data = await res.json()
      onAccept?.(reminder)
      // 移除已接受的提醒
      setReminders(prev => prev.filter(r => r.reminder_id !== reminder.reminder_id))
    } catch (err) {
      console.error('Failed to accept reminder:', err)
    }
  }

  const handleSnooze = async (reminderId: string) => {
    try {
      await fetch(`/api/reminders/${reminderId}/snooze`, {
        method: 'POST',
      })
      onSnooze?.(reminderId)
      // 移除已推迟的提醒
      setReminders(prev => prev.filter(r => r.reminder_id !== reminderId))
    } catch (err) {
      console.error('Failed to snooze reminder:', err)
    }
  }

  const handleDismiss = async (reminderId: string) => {
    try {
      await fetch(`/api/reminders/${reminderId}/dismiss`, {
        method: 'POST',
      })
      onDismiss?.(reminderId)
      // 添加到已忽略列表
      setDismissedIds(prev => new Set([...prev, reminderId]))
      setReminders(prev => prev.filter(r => r.reminder_id !== reminderId))
    } catch (err) {
      console.error('Failed to dismiss reminder:', err)
    }
  }

  if (loading || reminders.length === 0) {
    return null
  }

  const urgencyColors: Record<string, string> = {
    high: 'var(--red)',
    normal: 'var(--yellow)',
    low: 'var(--text-light)',
  }

  const typeIcons: Record<string, string> = {
    meal_time: '⏰',
    missed_meal: '🍽️',
    long_gap_without_food: '⏱️',
    nutrition_gap: '🥗',
    budget_available: '💰',
    late_night_warning: '🌙',
  }

  return (
    <div className="reminder-cards">
      {reminders.map((reminder) => (
        <div
          key={reminder.reminder_id}
          className="card reminder-card"
          style={{ borderLeftColor: urgencyColors[reminder.urgency] || 'var(--primary)' }}
        >
          <div className="reminder-header">
            <span className="reminder-icon">
              {typeIcons[reminder.type] || '💡'}
            </span>
            <span className="reminder-title">{reminder.title}</span>
          </div>

          <p className="reminder-message">{reminder.message}</p>

          <div className="reminder-actions">
            <button
              className="btn-reminder accept"
              onClick={() => handleAccept(reminder)}
            >
              帮我搭配
            </button>
            <button
              className="btn-reminder snooze"
              onClick={() => handleSnooze(reminder.reminder_id)}
            >
              稍后提醒
            </button>
            <button
              className="btn-reminder dismiss"
              onClick={() => handleDismiss(reminder.reminder_id)}
            >
              今天不吃了
            </button>
          </div>
        </div>
      ))}
    </div>
  )
}

// apps/web/src/components/ReminderCard.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Card, CardContent, Button } from '@/components/ui'
import { useNotifications } from '@/composables/useNotifications'
import { fetchReminders, acceptReminder, snoozeReminder, dismissReminder } from '@/api/client'

const props = defineProps<{ userId?: string }>()
const emit = defineEmits<{ 'accept': [reminder: any] }>()

const { requestPermission, notify, supported } = useNotifications()
const reminders = ref<any[]>([])
const dismissedIds = ref(new Set<string>())
const notifiedIds = ref(new Set<string>())

async function loadReminders() {
  try {
    const data = await fetchReminders(props.userId || 'demo-user')
    const filtered = (data.reminders || []).filter((r: any) => !dismissedIds.value.has(r.reminder_id))
    reminders.value = filtered
    if (supported.value) {
      requestPermission()
      const fresh = filtered.filter((r: any) => !notifiedIds.value.has(r.reminder_id))
      if (fresh.length > 0) {
        notify(fresh[0].title, { body: fresh[0].message })
        fresh.forEach((r: any) => notifiedIds.value.add(r.reminder_id))
      }
    }
  } catch {}
}

async function handleAccept(reminder: any) {
  await acceptReminder(reminder.reminder_id)
  emit('accept', reminder)
  reminders.value = reminders.value.filter(r => r.reminder_id !== reminder.reminder_id)
}

async function handleSnooze(id: string) {
  await snoozeReminder(id)
  reminders.value = reminders.value.filter(r => r.reminder_id !== id)
}

async function handleDismiss(id: string) {
  await dismissReminder(id)
  dismissedIds.value.add(id)
  reminders.value = reminders.value.filter(r => r.reminder_id !== id)
}

const urgencyColors: Record<string, string> = {
  high: 'border-l-red-500',
  normal: 'border-l-yellow-500',
  low: 'border-l-gray-300',
}
const typeIcons: Record<string, string> = {
  meal_time: '⏰',
  missed_meal: '🍽️',
  long_gap_without_food: '⏱️',
  nutrition_gap: '🥗',
  budget_available: '💰',
  late_night_warning: '🌙',
}

let interval: number
onMounted(() => {
  loadReminders()
  interval = window.setInterval(loadReminders, 2 * 60 * 1000)
})
onUnmounted(() => clearInterval(interval))
</script>

<template>
  <div v-if="reminders.length" class="space-y-3">
    <Card v-for="r in reminders" :key="r.reminder_id" :class="`border-l-4 ${urgencyColors[r.urgency] || 'border-l-gray-300'}`">
      <CardContent class="p-4 space-y-2">
        <div class="flex items-center gap-2">
          <span class="text-lg">{{ typeIcons[r.type] || '💡' }}</span>
          <span class="font-medium text-sm">{{ r.title }}</span>
        </div>
        <p class="text-sm text-gray-600">{{ r.message }}</p>
        <div class="flex gap-2">
          <Button size="sm" @click="handleAccept(r)">帮我搭配</Button>
          <Button size="sm" variant="outline" @click="handleSnooze(r.reminder_id)">稍后提醒</Button>
          <Button size="sm" variant="ghost" @click="handleDismiss(r.reminder_id)">今天不吃了</Button>
        </div>
      </CardContent>
    </Card>
  </div>
</template>
